### PR TITLE
Dev path finding BFS 2

### PR DESCRIPTION
**Pull request by ycMia**

### CODE REVIEW

**Comment by ycMia** [comment]
I must try sth to fix the searching structure. Well at the previous vision, I got an annoying Queue, then loop itself to check the prevois node. Terrible.
In this version I'll use a tree to Store them , the algorithm complexity of pre-searching will reduce to O(1) compared with O(n*QueueLength).

**Comment by ycMia** [comment]
Next term, I'll fix the Search(..) function into the Coroutine. That will smooth the frame rate

**Comment by buger404** [comment]
My appreciation & admiration is beyond expression !!! ❤❤❤❤

**Comment by ycMia** [comment]
> My appreciation & admiration is beyond expression !!! ❤❤❤❤

XD

**Comment by ycMia** [comment]
Dev path finding BFS 2 -- TreeStruct

**Pull request merged**
